### ISSUE TITLE
Tests fail on PHP 7

### ISSUE THREAD

**Issue by adduc** [dominionenterprises/memoize-php#16]
Because of [this RFC](https://wiki.php.net/rfc/reserve_even_more_types_in_php_7), 'Null' can no longer be used as a class name as of PHP 7.

Would you be opposed to adding a suffix to the classes implementing the Memoize interface? Something like NullMemoize?

**Comment by chrisryan** [comment]
I just opened a PR that should fix the problem. I don't have php7 installed yet so please let me know if this resolves the issues you were experiencing.

**Comment by adduc** [comment]
With your pull request, tests now pass in PHP 7, but there is an additional problem. composer.json needs to be updated to change PHP requirement from `~5.3` to `>= 5.3`

**Comment by chrisryan** [comment]
Updated PR with new name "Never" and updated composer php requiresments to ">=5.4"
